import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#0a6cce",
          50: "#eff8ff",
          100: "#dbeefe",
          200: "#bfe2fe",
          300: "#93d1fd",
          400: "#60b7fa",
          500: "#3b9df6",
          600: "#2584eb",
          700: "#1d6dd8",
          800: "#1e58af",
          900: "#0a6cce",
          950: "#164282",
          foreground: "#ffffff",
          dark: {
            DEFAULT: "#0a6cce",
            50: "#eff8ff",
            100: "#dbeefe",
            200: "#bfe2fe",
            300: "#93d1fd",
            400: "#60b7fa",
            500: "#3b9df6",
            600: "#2584eb",
            700: "#1d6dd8",
            800: "#1e58af",
            900: "#0a6cce",
            950: "#164282",
            foreground: "#000000",
          },
        },
        secondary: {
          DEFAULT: "#37abef",
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#37abef",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
          950: "#082f49",
          foreground: "#ffffff",
          dark: {
            DEFAULT: "#37abef",
            50: "#f0f9ff",
            100: "#e0f2fe",
            200: "#bae6fd",
            300: "#7dd3fc",
            400: "#37abef",
            500: "#0ea5e9",
            600: "#0284c7",
            700: "#0369a1",
            800: "#075985",
            900: "#0c4a6e",
            950: "#082f49",
            foreground: "#000000",
          },
        },
        tertiary: {
          DEFAULT: "#46c0fa",
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#46c0fa",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
          950: "#082f49",
          foreground: "#ffffff",
          dark: {
            DEFAULT: "#46c0fa",
            50: "#f0f9ff",
            100: "#e0f2fe",
            200: "#bae6fd",
            300: "#7dd3fc",
            400: "#46c0fa",
            500: "#0ea5e9",
            600: "#0284c7",
            700: "#0369a1",
            800: "#075985",
            900: "#0c4a6e",
            950: "#082f49",
            foreground: "#000000",
          },
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          dark: {
            DEFAULT: "hsl(var(--destructive-dark))",
            foreground: "hsl(var(--destructive-foreground-dark))",
          },
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
          dark: {
            DEFAULT: "hsl(var(--muted-dark))",
            foreground: "hsl(var(--muted-foreground-dark))",
          },
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          dark: {
            DEFAULT: "hsl(var(--accent-dark))",
            foreground: "hsl(var(--accent-foreground-dark))",
          },
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
          dark: {
            DEFAULT: "hsl(var(--popover-dark))",
            foreground: "hsl(var(--popover-foreground-dark))",
          },
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
          dark: {
            DEFAULT: "hsl(var(--card-dark))",
            foreground: "hsl(var(--card-foreground-dark))",
          },
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
